config/routes.rb
Leadslist::Application.routes.draw do
  resources :investors do
    resources :companies
  end


  resources :companies do 
    resources :investors
  end


get "home/company_profile"
get "home/investors"

  authenticated :user do
    root :to => 'companies#new'
  end

  root :to => "home#index"
  devise_for :users
  resources :users
end


# get "/companies/_form"

app/models/angel_list.rb
require 'httparty'
require 'hashie'

class AngelList
  include HTTParty
  base_uri "api.angel.co/1"

  # Usage
  # initialize api call
  # api = AngelList.new

  # Search 
  # api.search query: 'health care', type: "MarketTag"
  def search(options={})
    results = self.class.get "/search", query: options
    JSON.parse(results.body)
  end

  # Find users by tag
  # api.find_users_by_tag tag-id: '13'
  def find_users_by_tag(tag_id, options={})
     results = self.class.get "/tags/#{tag_id}/users", query: options
     JSON.parse(results.body)
  end

end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :financing_stage, :location, :market, :name

  belongs_to :user
  has_many :investors
end

app/models/investor.rb
class Investor < ActiveRecord::Base
  attr_accessible :angellist_image_url, :angellist_url, :bio, :company_name, :company_url, :email_address, :follower_count, :investment_status, :job_title, :location, :name, :phone_number, :company_id

  belongs_to :company
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  belongs_to :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])
    @investors = @company.investors.all
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/investors_controller.rb
class InvestorsController < ApplicationController
  # GET /investors
  # GET /investors.json
  def index
    @investors = Investor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @investors }
    end
  end

  # GET /investors/1
  # GET /investors/1.json
  def show
    @investor = Investor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @investor }
    end
  end

  # GET /investors/new
  # GET /investors/new.json
  def new
    @investor = Company.find(params[:company_id]).investors.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @investor }
    end
  end

  # GET /investors/1/edit
  def edit
    @investor = Investor.find(params[:id])
  end

  # POST /investors
  # POST /investors.json
  def create
    @investor = Investor.new(params[:investor])

    respond_to do |format|
      if @investor.save
        format.html { redirect_to @investor, notice: 'Investor was successfully created.' }
        format.json { render json: @investor, status: :created, location: @investor }
      else
        format.html { render action: "new" }
        format.json { render json: @investor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /investors/1
  # PUT /investors/1.json
  def update
    @investor = Investor.find(params[:id])

    respond_to do |format|
      if @investor.update_attributes(params[:investor])
        format.html { redirect_to @investor, notice: 'Investor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @investor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investors/1
  # DELETE /investors/1.json
  def destroy
    @investor = Investor.find(params[:id])
    @investor.destroy

    respond_to do |format|
      format.html { redirect_to investors_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/investors_helper.rb
module InvestorsHelper
end

app/views/companies/_form.html.erb
<%= simple_form_for(@company) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :location %>
    <%= f.input :market %>
    <%= f.input :financing_stage %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th>Market</th>
    <th>Financing stage</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @companies.each do |company| %>
  <tr>
    <td><%= company.name %></td>
    <td><%= company.location %></td>
    <td><%= company.market %></td>
    <td><%= company.financing_stage %></td>
    <td><%= link_to 'Show', company %></td>
    <td><%= link_to 'Edit', edit_company_path(company) %></td>
    <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>Create Your Company</h1>

<%= render 'form' %>

app/views/companies/show.html.erb
<h1><%= @company.name %></h1>


<div class="row well">
  <div class="col-md-6 text-center">
    <p>
      <b>Name:</b>
      <%= @company.name %>
    </p>

    <p>
      <b>Location:</b>
      <%= @company.location %>
    </p>    
  </div>
  <div class="col-md-6 text-center">
    <p>
      <b>Market:</b>
      <%= @company.market %>
    </p>
    <p>
      <b>Financing stage:</b>
      <%= @company.financing_stage %>
    </p>  
  </div>
  <%= link_to 'Edit Company Information', edit_company_path(@company), class: "pull-right" %>
</div>

<h4>Investor Summary</h4>
<div class="row well">
  <div class="col-md-3">
    <div class="panel panel-primary">
      <div class="panel-heading text-center">Total Investors</div>
      <div class="panel-body text-center">
        <%= @company.investors.count %>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="panel panel-success">
      <div class="panel-heading text-center">Committed Investors</div>
      <div class="panel-body text-center">
        <%= @company.investors.where(investment_status: "Yes").count %>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="panel panel-info">
      <div class="panel-heading text-center">Maybe Investors</div>
      <div class="panel-body text-center">
        <%= @company.investors.where(investment_status: "Maybe").count %>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="panel panel-danger">
      <div class="panel-heading text-center">Rejected Investors</div>
      <div class="panel-body text-center">
        <%= @company.investors.where(investment_status: "No").count %>
      </div>
    </div>
  </div>
</div>
<br>
<h4>Investor Profiles</h4>
<div class="row">
<% @investors.each do |investor| %>
  <div class="well col-md-3">
    <p><%= investor.name %></p>
    <p><%= investor.email_address %></p>
    <p><%= investor.phone_number %></p>
    <p><%= investor.job_title + ", " + investor.company_name %></p>
    <%= link_to investor.company_name, company_url %>
  </div>
<% end %>
</div>
<hr>
<hr>
<br>
<div class="col-md-6 col-md-offset-3">
<%= link_to 'Add New Investor', new_company_investor_path(@company), class: "btn btn-primary btn-lg center-block" %>
</div>

app/views/home/company_profile.html.erb
<div class="container">

        <div class="jumbotron hero-spacer">
            <h1><%= @company.name %></h1>
            <p>Introduce your website content using this jumbotron! It's an awesome way to call attention to something that needs to be read! It's also a great alternative to using a banner image if you don't have a good quality picture!</p>
            <p><a class="btn btn-primary btn-large">Add Investor</a>
            </p>
        </div>

        <hr>

        <div class="row">
            <div class="col-lg-12">
                <h3>Latest Features</h3>
            </div>
        </div>
        <!-- /.row -->

        <div class="row text-center">

            <div class="col-lg-3 col-md-6 hero-feature">
                <div class="thumbnail">
                    <img src="http://placehold.it/800x500" alt="">
                    <div class="caption">
                        <h3>Investor One</h3>
                        <p>Details from database</p>
                        <p><a href="#" class="btn btn-primary">Pull up info</a><a href="#" class="btn btn-default">See more</a>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 hero-feature">
                <div class="thumbnail">
                    <img src="http://placehold.it/800x500" alt="">
                    <div class="caption">
                        <h3>Investor Two</h3>
                        <p>This would be a great spot to feature some brand new products!</p>
                        <p><a href="#" class="btn btn-primary">Buy Now!</a>  <a href="#" class="btn btn-default">More Info</a>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 hero-feature">
                <div class="thumbnail">
                    <img src="http://placehold.it/800x500" alt="">
                    <div class="caption">
                        <h3>Investor Three</h3>
                        <p>This would be a great spot to feature some brand new products!</p>
                        <p><a href="#" class="btn btn-primary">Buy Now!</a>  <a href="#" class="btn btn-default">More Info</a>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 hero-feature">
                <div class="thumbnail">
                    <img src="http://placehold.it/800x500" alt="">
                    <div class="caption">
                        <h3>Feature Label</h3>
                        <p>This would be a great spot to feature some brand new products!</p>
                        <p><a href="#" class="btn btn-primary">Buy Now!</a>  <a href="#" class="btn btn-default">More Info</a>
                        </p>
                    </div>
                </div>
            </div>


        </div>
        <!-- /.row -->

        <hr>

        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Track My Investor 2013</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

    <!-- JavaScript -->
    <script src="js/jquery-1.10.2.js"></script>
    <script src="js/bootstrap.js"></script>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Investor CRM for Startups</title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.css" rel="stylesheet">

    <!-- Add custom CSS here -->
    <link href="css/stylish-portfolio.css" rel="stylesheet">
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet">
</head>

<body>

    <!-- Full Page Image Header Area -->
    <div id="top" class="header">
        <div class="vert-text">
           <br>
           <br>
           <br>
            <h1>LeadsList.co</h1>
            <h3>
               Investor CRM for Startups. Moving beyond the Excel era.<br>
                <br>
                <br>
            <%= link_to "Get Started Now", '/users/sign_up', class: "btn btn-default btn-lg" %>
            <!-- <a href="#about" class="btn btn-default btn-lg">Get Started Now</a><%= link_to new_user_path %> -->
        </div>
    </div>
    <!-- /Full Page Image Header Area -->
    <br>
    <br>
    <br>
    <!-- Services -->
    <div id="services" class="services">
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-md-offset-4 text-center">
                    <h2>Why Use LeadsList?</h2>
                    <hr>
                </div>
            </div>
            <div class="row">
                <div class="col-md-2 col-md-offset-2 text-center">
                    <div class="service-item">
                        <i class="service-icon fa fa-rocket"></i>
                        <h4>Easy to Use</h4>
                        <p>Super easy to use and much better than the traditional Excel spreadsheets</p>
                    </div>
                </div>
                <div class="col-md-2 text-center">
                    <div class="service-item">
                        <i class="service-icon fa fa-magnet"></i>
                        <h4>Share with Team</h4>
                        <p>Much easy way to track and share the status with your team and current investors </p>
                    </div>
                </div>
                <div class="col-md-2 text-center">
                    <div class="service-item">
                        <i class="service-icon fa fa-shield"></i>
                        <h4>Find More Investors</h4>
                        <p>We suggest investors that you didn't even know existed who we know are interested in your industry</p>
                    </div>
                </div>
                <div class="col-md-2 text-center">
                    <div class="service-item">
                        <i class="service-icon fa fa-pencil"></i>
                        <h4>Track Your Stats</h4>
                        <p>Get updated stats in real time. Know your conversion rate and other relevant stats</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /Services -->

    <!-- Call to Action -->
    <div class="call-to-action">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3 text-center">
                    <h3>Cool Right? Still Interested?</h3>
                    <a href="#" class="btn btn-lg btn-primary">Get Started</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3 text-center">
                    <p>Copyright &copy; LeadsList 2014</p>
                </div>
            </div>
        </div>
    </footer>
    <!-- /Footer -->
</body>

</html>

app/views/home/investors.html.erb
 <div class="container">

        <div class="row">

            <div class="col-lg-12">
                <h1 class="page-header">About Us
                    <small>It's Nice to Meet You!</small>
                </h1>
                <p>This is a great place to start off with a short and sweet description of your company, organization, or whatever purpose your website is serving. Keep it friendly, engaging, but short enough to where you won't lose your reader!</p>
                <p>If you need a bit more space to describe what is going on, we recommend putting a picture in this section. Use the
                    <code>pull-right</code>class on the image to make it look good!</p>
            </div>

            <div class="col-lg-12">
                <h2 class="page-header">Our Team</h2>
            </div>

        </div>

        <div class="row">
            <div class="col-lg-4 col-sm-6">
                <img class="img-circle img-responsive" src="http://placehold.it/200x200">
                <h3>John Smith
                    <small>Job Title</small>
                </h3>
                <p>What does this team member to? Keep it short! This is also a great spot for social links!</p>
            </div>
            <div class="col-lg-4 col-sm-6">
                <img class="img-circle img-responsive" src="http://placehold.it/200x200">
                <h3>John Smath
                    <small>Job Title</small>
                </h3>
                <p>What does this team member to? Keep it short! This is also a great spot for social links!</p>
            </div>
            <div class="col-lg-4 col-sm-6">
                <img class="img-circle img-responsive" src="http://placehold.it/200x200">
                <h3>John Smeth
                    <small>Job Title</small>
                </h3>
                <p>What does this team member to? Keep it short! This is also a great spot for social links!</p>
            </div>
            <div class="col-lg-4 col-sm-6">
                <img class="img-circle img-responsive" src="http://placehold.it/200x200">
                <h3>John Smyth
                    <small>Job Title</small>
                </h3>
                <p>What does this team member to? Keep it short! This is also a great spot for social links!</p>
            </div>
            <div class="col-lg-4 col-sm-6">
                <img class="img-circle img-responsive" src="http://placehold.it/200x200">
                <h3>John Smoth
                    <small>Job Title</small>
                </h3>
                <p>What does this team member to? Keep it short! This is also a great spot for social links!</p>
            </div>
            <div class="col-lg-4 col-sm-6">
                <img class="img-circle img-responsive" src="http://placehold.it/200x200">
                <h3>John Smuth
                    <small>Job Title</small>
                </h3>
                <p>What does this team member to? Keep it short! This is also a great spot for social links!</p>
            </div>
        </div>

        <hr>

        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Company 2013</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /container -->

    <!-- JavaScript -->
    <script src="js/jquery-1.10.2.js"></script>
    <script src="js/bootstrap.js"></script>

app/views/investors/_form.html.erb
<%= simple_form_for(@investor) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class='hide'>
      <%= f.association :company, selected: params[:company_id] %>
    </div>
    <%= f.input :name %>
    <%#= f.input :bio %>
    <%#= f.input :follower_count %>
    <%#= f.input :angellist_url %>
    <%#= f.input :angellist_image_url %>
    <%#= f.input :location %>
    <%= f.input :email_address %>
    <%= f.input :phone_number %>
    <%= f.input :job_title, collection: ["Partner","Principal","Analyst","Angel","Friends & Family"], include_blank: false %>
    <%= f.input :company_name %>
    <%#= f.input :company_url %>
    <%= f.input :investment_status, collection: ["Yes","No","Maybe"], include_blank: false %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/investors/edit.html.erb
<h1>Editing investor</h1>

<%= render 'form' %>

<%= link_to 'Show', @investor %> |
<%= link_to 'Back', investors_path %>

app/views/investors/index.html.erb
<h1>Potential Investors</h1>
<h3>Select investors from the list to add them to your LeadsList</h3>

<table>
  <tr>
    <th>Name</th>
    <th>Bio</th>
    <th>Follower count</th>
    <th>Angellist url</th>
    <th>Angellist image url</th>
    <th>Location</th>
    <th>Email address</th>
    <th>Phone number</th>
    <th>Job title</th>
    <th>Company name</th>
    <th>Company url</th>
    <th>Investment status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @investors.each do |investor| %>
  <tr>
    <td><%= investor.name %></td>
    <td><%= investor.bio %></td>
    <td><%= investor.follower_count %></td>
    <td><%= investor.angellist_url %></td>
    <td><%= investor.angellist_image_url %></td>
    <td><%= investor.location %></td>
    <td><%= investor.email_address %></td>
    <td><%= investor.phone_number %></td>
    <td><%= investor.job_title %></td>
    <td><%= investor.company_name %></td>
    <td><%= investor.company_url %></td>
    <td><%= investor.investment_status %></td>
    <td><%= link_to 'Show', investor %></td>
    <td><%= link_to 'Edit', edit_investor_path(investor) %></td>
    <td><%= link_to 'Destroy', investor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
<h3>If you can't find an investor above, you can create an investor for your LeadsList</h3>

<%= link_to 'Create A New Investor', new_investor_path %>
<br>
<%= link_to 'Return to your Company Profile', companies_path %>

app/views/investors/new.html.erb
<h1>New investor</h1>

<%= render 'form' %>

<%= link_to 'Back', investors_path %>

app/views/investors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @investor.name %>
</p>

<p>
  <b>Bio:</b>
  <%= @investor.bio %>
</p>

<p>
  <b>Follower count:</b>
  <%= @investor.follower_count %>
</p>

<p>
  <b>Angellist url:</b>
  <%= @investor.angellist_url %>
</p>

<p>
  <b>Angellist image url:</b>
  <%= @investor.angellist_image_url %>
</p>

<p>
  <b>Location:</b>
  <%= @investor.location %>
</p>

<p>
  <b>Email address:</b>
  <%= @investor.email_address %>
</p>

<p>
  <b>Phone number:</b>
  <%= @investor.phone_number %>
</p>

<p>
  <b>Job title:</b>
  <%= @investor.job_title %>
</p>

<p>
  <b>Company name:</b>
  <%= @investor.company_name %>
</p>

<p>
  <b>Company url:</b>
  <%= @investor.company_url %>
</p>

<p>
  <b>Investment status:</b>
  <%= @investor.investment_status %>
</p>

<%= link_to 'Back to Company', company_path(@investor.company_id) %> |
<%= link_to 'Edit', edit_investor_path(@investor) %> |
<%= link_to 'Back', investors_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'LEADSlist', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
  <li> <%= link_to "Browse Investors", home_investors_path%>
  <li><%#= link_to "Browse Investors", investors_path %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
<% else %>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Leadslist" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Leadslist" %>">
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </div>
  </body>
</html>

app/views/users/index.html.erb
<h3>Users</h3>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>
<%= link_to 'Edit account', edit_user_path %>